INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Aquaman','Modern','Arthur Curry','Human','Hero','Male','Telepathy;Hydrokinetic;Communicate with Marine Animals','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Archangel','Modern','Warren Worthington III','Mutant','Hero','Male','Healing Factor;Flight','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Batman','Modern','Bruce Wayne','Human','Hero','Male','Genius;Money','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Beast','Modern','Hank McCoy','Mutant','Hero','Male','Genius;Animal Like','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Black Widow','Modern','Natasha Romanoff','Human','Hero','Female','Combat','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Captain America','Modern','Steve Rogers','Human','Hero','Male','Strength;Endurance','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Cyclops','Modern','Scott Summers','Mutant','Hero','Male','Lasers','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Doctor Doom','Modern','Viktor Krumm','Human','Villian','Male','Technopathy;Genius;Flight;Force Fields','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Doctor Octopus','Modern','Otto Gunther Octavius','Human','Villian','Male','Genius','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('The Flash','Modern','Wally West','Human','Hero','Male','Speed','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('The Flash','Silver','Barry Allen','Human','Hero','Male','Speed','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Green Lantern','Modern','Kyle Rayner','Human','Hero','Male','Power Ring','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Green Lantern','Silver','Hal Jordan','Human','Hero','Male','Power Ring','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Hawkeye','Modern','Clint Barton','Human','Hero','Male','Archery','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Hulk','Modern','Bruce Banner','Human','Hero','Male','Genius;Strength','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Human Torch','Modern','Johnny Storm','Human','Hero','Male','Pyrokinesis','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Iceman','Modern','Bobby Drake','Mutant','Hero','Male','Thermal Vision;Tranform to Ice;Generate Ice','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Invisible Woman','Modern','Susan Storm','Human','Hero','Female','Force Fields','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Iron Man','Modern','Tony Stark','Human','Hero','Male','Genius;Money','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Magneto','Modern','Erik Lehnsherr','Mutant','Hero','Male','Magnetism','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Mister Fantastic','Modern','Reed Richards','Human','Hero','Male','Genius;Elasticity','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Phoenix','Modern','Jean Grey','Mutant','Hero','Female','Telekinesis;Telepathy;Phoenix Force','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Professor X','Modern','Charles Xavier','Mutant','Hero','Male','Telepathy','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Quicksilver','Modern','Pietro Maximoff','Mutant','Hero','Male','Speed','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Scarlet Witch','Modern','Wanda Maximoff','Mutant','Hero','Female','Reality Warping','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Storm','Modern','Ororo Monroe','Mutant','Hero','Female','Weather Control;Flight','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Superman','Modern','Clark Kent','Kryptonian','Hero','Male','Strength;Flight','Krypton');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('The Thing','Modern','Ben Grimm','Human','Hero','Male','Strength;Endurance','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Thor','Modern','Thor Odinson','Asgardian','Hero','Male','Mjolnr;God','Asgard');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Wolverine','Modern','Logan Howlett','Mutant','Hero','Male','Healing Factor','Earth');
INSERT INTO SuperheroesAndStuff_kharacter VALUES ('Wonder Woman','Modern','Princess Diana of Themyscira','Amazon','Hero','Female','Strength;Agility;Flight;Endurance','Earth');